//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class AwardsOfParticipant
    {
        public int id_awards_of_participants { get; set; }
        public Nullable<int> id_participant { get; set; }
        public Nullable<int> id_reward { get; set; }
    
        public virtual Award Award { get; set; }
        public virtual ParticipantsOfTheWar ParticipantsOfTheWar { get; set; }
    }
}
