//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParticipantsOfTheWar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ParticipantsOfTheWar()
        {
            this.AwardsOfParticipants = new HashSet<AwardsOfParticipant>();
            this.ParticipantsWorks = new HashSet<ParticipantsWork>();
        }
    
        public int id_participant { get; set; }
        public string surname { get; set; }
        public string name { get; set; }
        public string patronymic { get; set; }
        public Nullable<int> id_gender { get; set; }
        public string date_of_birth { get; set; }
        public string date_of_death { get; set; }
        public string place_of_appeal { get; set; }
        public Nullable<int> id_ranks { get; set; }
        public string place_of_service { get; set; }
        public string place_of_birth { get; set; }
        public byte[] photo { get; set; }
        public string biography { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AwardsOfParticipant> AwardsOfParticipants { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual MilitaryRank MilitaryRank { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParticipantsWork> ParticipantsWorks { get; set; }
    }
}
