//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParticipantsWork
    {
        public int id_participants_work { get; set; }
        public Nullable<int> id_participant { get; set; }
        public Nullable<int> id_post { get; set; }
        public Nullable<int> id_place_of_work { get; set; }
        public Nullable<decimal> start_of_work { get; set; }
        public Nullable<decimal> end_of_work { get; set; }
        public string description { get; set; }
    
        public virtual ParticipantsOfTheWar ParticipantsOfTheWar { get; set; }
        public virtual PlaceOfWork PlaceOfWork { get; set; }
        public virtual Post Post { get; set; }
    }
}
